In [1]:
import numpy as np
from matplotlib import pyplot as plt
import cv2
import glob

import math
from scipy import linalg
from numpy.linalg import inv
from sklearn import linear_model, datasets
from function import *

In [2]:
img_p = return_imagepoints()
obj_p = return_objpoints()

p = projection_matrix_direct(img_p,obj_p)
p

array([[ 2.35641141e+01, -1.13180327e-01,  1.07795469e+02],
       [ 1.24120961e-01,  2.34434472e+01,  8.29785775e+01],
       [ 2.21177243e-17, -6.93889390e-17,  1.00000000e+00]])

In [3]:
p = projection_matrix(img_p,obj_p)
p

array([[ 2.32708135e+01, -6.48353739e-02,  1.08385471e+02],
       [-1.23646156e-02,  2.33727681e+01,  8.37870163e+01],
       [-5.46339618e-04,  1.40990039e-04,  1.00000000e+00]])

In [8]:
img_homo = np.ones((3,315))
img_homo[0,:] = img_p[:,0]
img_homo[1,:] = img_p[:,1]

obj_homo3 = np.ones((3,315))
obj_homo3[0,:] = obj_p[:,0]
obj_homo3[1,:] = obj_p[:,1]
# obj_homo3

In [11]:
im_pre = np.matmul(H,obj_homo3)
im_pre[:,:30]

array([[108.38547135, 131.65628486, 154.92709836, 178.19791186,
        201.46872537, 224.73953887, 248.01035238, 271.28116588,
        294.55197938, 317.82279289, 341.09360639, 364.3644199 ,
        387.6352334 , 410.90604691, 434.17686041, 457.44767391,
        480.71848742, 503.98930092, 527.26011443, 550.53092793,
        573.80174144, 108.32063598, 131.59144948, 154.86226299,
        178.13307649, 201.40388999, 224.6747035 , 247.945517  ,
        271.21633051, 294.48714401],
       [ 83.78701628,  83.77465166,  83.76228705,  83.74992243,
         83.73755781,  83.7251932 ,  83.71282858,  83.70046397,
         83.68809935,  83.67573474,  83.66337012,  83.6510055 ,
         83.63864089,  83.62627627,  83.61391166,  83.60154704,
         83.58918243,  83.57681781,  83.5644532 ,  83.55208858,
         83.53972396, 107.15978439, 107.14741977, 107.13505516,
        107.12269054, 107.11032593, 107.09796131, 107.08559669,
        107.07323208, 107.06086746],
       [  1.        ,   0.9994

In [13]:
img_homo[:,:30]

array([[107.56755066, 130.83979797, 154.64964294, 178.43469238,
        202.1711731 , 225.64862061, 249.3981781 , 273.0770874 ,
        296.48498535, 319.58239746, 343.1633606 , 366.5144043 ,
        389.93441772, 413.60021973, 437.34890747, 461.1373291 ,
        485.06295776, 509.17733765, 533.06195068, 557.16821289,
        580.50585938, 107.33692169, 130.93611145, 154.7782135 ,
        178.62882996, 202.2800293 , 225.58125305, 249.2624054 ,
        272.77856445, 296.31332397],
       [ 83.28165436,  83.35715485,  83.52548218,  83.59564972,
         84.16691589,  84.19496155,  84.3937149 ,  84.56157684,
         84.66824341,  84.62976837,  84.49532318,  84.71075439,
         84.65130615,  84.61601257,  84.27425385,  84.37445831,
         84.3088913 ,  84.09620667,  83.88614655,  83.61513519,
         83.75165558, 106.62995148, 106.88222504, 107.22281647,
        107.39172363, 107.50106812, 107.51467896, 107.59059143,
        107.61261749, 107.84807587],
       [  1.        ,   1.    