In [1]:
import numpy as np
from matplotlib import pyplot as plt
import cv2
import glob

import math
from scipy import linalg
from numpy.linalg import inv
from numpy import linalg as LA
from sklearn import linear_model, datasets
from function import *

[[ 2.32708135e+01 -6.48353739e-02  1.08385471e+02]
 [-1.23646156e-02  2.33727681e+01  8.37870163e+01]
 [-5.46339618e-04  1.40990039e-04  1.00000000e+00]]


In [2]:
img_p = return_imagepoints()
obj_p = return_objpoints()

obj_p4 = homo_obj4(obj_p)
obj_p3 = homo_obj3(obj_p)
img_p = homo_img(img_p)

print("obj_p3.shape", obj_p3.shape)
print("obj_p4.shape", obj_p4.shape)
print("img_p.shape", img_p.shape)

obj_p3.shape (3, 315)
obj_p4.shape (4, 315)
img_p.shape (3, 315)


In [3]:
obj_pt3 = obj_p3.T
obj_pt4 = obj_p4.T
img_pt = img_p.T
print("obj_pt.shape", obj_pt3.shape)
print("obj_pt.shape", obj_pt4.shape)
print("img_pt.shape", img_pt.shape)

obj_pt.shape (315, 3)
obj_pt.shape (315, 4)
img_pt.shape (315, 3)


In [4]:
# C = []

In [5]:
# for i in range(315):
#     C.append(np.array([obj_p[i,0], obj_p[i,1], obj_p[i,2],1,0,0,0,0,(-1)*obj_p[i,0]*img_p[i,0],
#                        (-1)*obj_p[i,1]*img_p[i,0],(-1)*obj_p[i,2]*img_p[i,0], (-1)*img_p[i,0]]))
        
#     C.append(np.array([0,0,0,0, obj_p[i,0], obj_p[i,1], obj_p[i,2],1,(-1)*obj_p[i,0]*img_p[i,1],
#                        (-1)*obj_p[i,1]*img_p[i,1], (-1)*obj_p[i,2]*img_p[i,1],(-1)*img_p[i,1]]))

In [6]:
# c = np.array(C)
# c.shape
# ctc = np.matmul(c.T,c)
# ctc.shape
# u, s, vh = np.linalg.svd(ctc, full_matrices=True)
# L = vh[-1]
# H = L.reshape(3, 4)
# H
# L = vh[-2]
# H = L.reshape(3,4)
# H = H/H[-1,-1]
# H
# vh

In [7]:
# output = 3x4 projection_matrix, input image shape=(num_points,2); obj shape=(num_points,3) 
def projection_matrix4(img_p, obj_p):
    
    C = []

    for i in range(315):
        C.append(np.array([obj_p[i,0], obj_p[i,1], obj_p[i,2],1,0,0,0,0,(-1)*obj_p[i,0]*img_p[i,0], 
                           (-1)*obj_p[i,1]*img_p[i,0],(-1)*obj_p[i,2]*img_p[i,0], (-1)*img_p[i,0]]))
        
        C.append(np.array([0,0,0,0, obj_p[i,0], obj_p[i,1], obj_p[i,2],1,(-1)*obj_p[i,0]*img_p[i,1], 
                           (-1)*obj_p[i,1]*img_p[i,1], (-1)*obj_p[i,2]*img_p[i,1],(-1)*img_p[i,1]]))
    
    c = np.array(C)
    ctc = np.matmul(c.T,c)
    u, s, vh = np.linalg.svd(ctc, full_matrices=True)
    L = vh[-2]
    H = L.reshape(3, 4)
# norm along y-axis
#     norm0 = LA.norm(H,axis=0)
#     H = H/norm0
#     norm1 = LA.norm(H,axis=1)
#     H = H/norm1 
#     norm = LA.norm(H)
#     H = H/norm
    
    H = H/H[-1,-1]
    
    return H

In [8]:

# norm = LA.norm(p12,axis=0)
# print(norm)
# p = p12/norm
# p

In [9]:
p = projection_matrix_direct(img_pt,obj_pt3)
print(p,"\n")

p_ = projection_matrix3(img_pt,obj_pt3)
print(p_,"\n")
_p = projection_matrix4(img_pt,obj_pt4)
print(_p)
# im_pre = np.matmul(H,obj_homo3)
# print(im_pre[:,:30])
# print(img_homo[:,:30])

[[ 2.35641141e+01 -1.13180327e-01  1.07795469e+02]
 [ 1.24120961e-01  2.34434472e+01  8.29785775e+01]
 [ 2.21177243e-17 -6.93889390e-17  1.00000000e+00]] 

[[ 2.32708135e+01 -6.48353739e-02  1.08385471e+02]
 [-1.23646156e-02  2.33727681e+01  8.37870163e+01]
 [-5.46339618e-04  1.40990039e-04  1.00000000e+00]] 

[[ 2.32809753e+01 -5.97991478e-02  3.55832089e+09  1.08329258e+02]
 [-8.60549440e-03  2.33812013e+01 -9.73293087e+12  8.37485083e+01]
 [-5.33408140e-04  1.52724823e-04  0.00000000e+00  1.00000000e+00]]


In [10]:
test3 = np.matmul(inv(p_),img_p)
test3[:,:5]

array([[-0.03513282,  0.96239668,  1.98298287,  3.00249183,  4.01999264],
       [-0.02158251, -0.0197773 , -0.01403147, -0.01248598,  0.01051265],
       [ 0.99998385,  1.00052858,  1.00108536,  1.00164214,  1.0021948 ]])

In [22]:
te = np.matmul(_p,obj_p4)
te

array([[108.3292576 , 131.6102329 , 154.8912082 , 178.17218351,
        201.45315881, 224.73413411, 248.01510942, 271.29608472,
        294.57706002, 317.85803533, 341.13901063, 364.41998593,
        387.70096124, 410.98193654, 434.26291185, 457.54388715,
        480.82486245, 504.10583776, 527.38681306, 550.66778836,
        573.94876367, 108.26945845, 131.55043375, 154.83140906,
        178.11238436, 201.39335966, 224.67433497, 247.95531027,
        271.23628557, 294.51726088, 317.79823618, 341.07921148,
        364.36018679, 387.64116209, 410.92213739, 434.2031127 ,
        457.484088  , 480.7650633 , 504.04603861, 527.32701391,
        550.60798921, 573.88896452, 108.2096593 , 131.4906346 ,
        154.77160991, 178.05258521, 201.33356051, 224.61453582,
        247.89551112, 271.17648643, 294.45746173, 317.73843703,
        341.01941234, 364.30038764, 387.58136294, 410.86233825,
        434.14331355, 457.42428885, 480.70526416, 503.98623946,
        527.26721476, 550.54819007, 573.

In [15]:
img_p

array([[107.56755066, 130.83979797, 154.64964294, 178.43469238,
        202.1711731 , 225.64862061, 249.3981781 , 273.0770874 ,
        296.48498535, 319.58239746, 343.1633606 , 366.5144043 ,
        389.93441772, 413.60021973, 437.34890747, 461.1373291 ,
        485.06295776, 509.17733765, 533.06195068, 557.16821289,
        580.50585938, 107.33692169, 130.93611145, 154.7782135 ,
        178.62882996, 202.2800293 , 225.58125305, 249.2624054 ,
        272.77856445, 296.31332397, 319.44625854, 342.96151733,
        366.31173706, 389.64541626, 413.41949463, 437.02697754,
        461.16882324, 484.8119812 , 508.94085693, 532.95355225,
        556.81744385, 580.48657227, 107.47132111, 130.70368958,
        154.64413452, 178.45004272, 201.51760864, 225.46687317,
        249.30691528, 272.87945557, 296.28707886, 319.3296814 ,
        342.8117981 , 366.140625  , 389.55459595, 413.24215698,
        437.009552  , 460.9944458 , 484.82711792, 509.11346436,
        532.95703125, 556.80236816, 580.

In [16]:
ptp = np.matmul(_p.T,_p)
ptpinv = inv(ptp)
pinv = np.matmul(ptpinv,_p.T)
test4 = np.matmul(pinv, img_p)
test4[:,:5]

NameError: name '_p' is not defined

In [17]:
obj_p4[:,:5]

array([[0., 1., 2., 3., 4.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.]])