In [1]:
import numpy as np
from matplotlib import pyplot as plt
import cv2
import glob

import math
from scipy import linalg
from numpy.linalg import inv
from numpy import linalg as LA
from sklearn import linear_model, datasets
from function import *

In [2]:
grid_x=21
grid_y=15
grid=(21,15)

objpoints = [] 
imgpoints = []

 
cap = cv2.VideoCapture(0)
while(True):
    try:
        ret, frame = cap.read()
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
 
        obj_pt3x4 = return_objpoints(grid)
        ret,img_pt, corners = return_imgGraypoints(gray,grid)
        if(not ret):
            cv2.imshow('frame',gray)
            if cv2.waitKey(10) & 0xFF == ord('q'):
                break
            continue
 
        cv2.drawChessboardCorners(gray, grid, corners,True)
    
        P = projection_matrix4(img_pt,obj_pt3x4)
     
        proj_px = img_projection(P, np.array([[0,0,0],[0,0,10],[10,0,0],[0,10,0]]))
        proj_px = np.clip(proj_px/proj_px[2],0,1000)   
        proj_px=proj_px.astype("uint8")
        print(proj_px)



        cv2.line(gray,tuple(proj_px.T[0][:2]),tuple(proj_px.T[1][:2]),(0,255,0),5)
        cv2.line(gray,tuple(proj_px.T[0][:2]),tuple(proj_px.T[2][:2]),(0,255,0),5)
        cv2.line(gray,tuple(proj_px.T[0][:2]),tuple(proj_px.T[3][:2]),(0,255,0),5)

        cv2.imshow('frame',gray)
        if cv2.waitKey(10) & 0xFF == ord('q'):
               break

    except KeyboardInterrupt:
        cap.release()
        cv2.destroyAllWindows()

image/corner doesnt exist
image/corner doesnt exist
image/corner doesnt exist
[[215   0 114 207]
 [142 232 149  41]
 [  1   1   1   1]]
[[192   0  88 191]
 [126   0 125  20]
 [  1   1   1   1]]
[[198   0  93 195]
 [120   0 121  15]
 [  1   1   1   1]]
[[204   0 102 203]
 [120   0 121  18]
 [  1   1   1   1]]
[[210   0 109 209]
 [119   0 120  19]
 [  1   1   1   1]]
[[215   0 116 214]
 [119 232 120  21]
 [  1   1   1   1]]
[[215   0 117 214]
 [119   0 120  21]
 [  1   1   1   1]]
[[216 232 118 214]
 [120 232 122  22]
 [  1   1   1   1]]
[[218   0 119 215]
 [120   0 123  22]
 [  1   1   1   1]]
[[219   0 120 217]
 [121 232 123  23]
 [  1   1   1   1]]
[[218   0 119 216]
 [122 232 123  22]
 [  1   1   1   1]]
[[215   0 114 213]
 [121 232 122  20]
 [  1   1   1   1]]
[[212   0 111 211]
 [121   0 121  19]
 [  1   1   1   1]]
[[209 232 107 209]
 [120   0 120  18]
 [  1   1   1   1]]
[[207 232 106 207]
 [119   0 119  18]
 [  1   1   1   1]]
[[207 232 105 207]
 [119   0 119  18]
 [  1   1   1 

[[ 27 232 125   3]
 [ 36 232  60 133]
 [  1   1   1   1]]
[[ 32   0 130  14]
 [ 53 232  71 150]
 [  1   1   1   1]]
[[ 38 232 135  24]
 [ 67 232  79 163]
 [  1   1   1   1]]
[[235 232 136 236]
 [125   0 125  28]
 [  1   1   1   1]]
[[247 232 146 240]
 [128 232 134  29]
 [  1   1   1   1]]
[[ 34 232 185   3]
 [146   0 177  42]
 [  1   1   1   1]]
[[ 41   0 190   5]
 [149 232 185  44]
 [  1   1   1   1]]
[[ 46 232 194   6]
 [152   0 191  45]
 [  1   1   1   1]]
[[ 48   0 196   5]
 [154 232 195  46]
 [  1   1   1   1]]
[[ 48 232 197   4]
 [153 232 195  47]
 [  1   1   1   1]]
[[ 47   0 196   3]
 [153   0 195  46]
 [  1   1   1   1]]
[[ 46 232 196   2]
 [153 232 195  46]
 [  1   1   1   1]]
[[ 48 232 197   2]
 [154   0 198  46]
 [  1   1   1   1]]
[[ 49   0 198   2]
 [154 232 199  47]
 [  1   1   1   1]]
[[ 49   0 199   2]
 [154   0 200  47]
 [  1   1   1   1]]
[[ 49   0 199   1]
 [154   0 200  47]
 [  1   1   1   1]]
[[ 49   0 199   1]
 [154 232 200  48]
 [  1   1   1   1]]
[[ 48   0 198 

[[ 23 232 179 212]
 [ 97   0 164 251]
 [  1   1   1   1]]
[[ 24 232 180 212]
 [ 98 232 166 252]
 [  1   1   1   1]]
[[ 23   0 180 212]
 [ 98 232 166 253]
 [  1   1   1   1]]
[[ 23 232 180 212]
 [ 98 232 165 253]
 [  1   1   1   1]]
[[ 24   0 180 212]
 [ 98 232 166 253]
 [  1   1   1   1]]
[[ 24 232 180 212]
 [ 99 232 166 253]
 [  1   1   1   1]]
[[ 23 232 179 211]
 [ 99   0 166 253]
 [  1   1   1   1]]
[[ 22   0 178 210]
 [ 99 232 166 253]
 [  1   1   1   1]]
[[ 21   0 178 210]
 [ 99 232 166 253]
 [  1   1   1   1]]
[[ 21   0 177 210]
 [ 99   0 166 253]
 [  1   1   1   1]]
[[ 22   0 179 212]
 [ 99 232 166 253]
 [  1   1   1   1]]
[[ 22   0 179 212]
 [ 99   0 165 253]
 [  1   1   1   1]]
[[ 22   0 178 213]
 [ 99   0 163 252]
 [  1   1   1   1]]
[[ 21 232 177 212]
 [ 99   0 163 252]
 [  1   1   1   1]]
[[ 21 232 177 212]
 [ 99   0 163 253]
 [  1   1   1   1]]
[[ 21 232 178 211]
 [ 99 232 164 254]
 [  1   1   1   1]]
[[ 19   0 176 210]
 [ 98   0 163 253]
 [  1   1   1   1]]
[[ 18   0 176 

[[ 48 232 190 232]
 [107 232 180 247]
 [  1   1   1   1]]
[[ 49   0 191 233]
 [106   0 179 247]
 [  1   1   1   1]]
[[ 49   0 191 233]
 [107 232 180 247]
 [  1   1   1   1]]
[[ 48 232 190 233]
 [108   0 180 248]
 [  1   1   1   1]]
[[ 48 232 190 232]
 [108   0 180 248]
 [  1   1   1   1]]
[[ 48   0 190 232]
 [108 232 181 248]
 [  1   1   1   1]]
[[ 48   0 189 232]
 [108 232 181 247]
 [  1   1   1   1]]
[[ 47 232 189 231]
 [108 232 181 248]
 [  1   1   1   1]]
[[ 47 232 189 231]
 [108   0 181 248]
 [  1   1   1   1]]
[[ 47   0 189 231]
 [108 232 181 247]
 [  1   1   1   1]]
[[ 48   0 189 232]
 [107 232 181 247]
 [  1   1   1   1]]
[[ 48   0 190 232]
 [107 232 180 247]
 [  1   1   1   1]]
[[ 49 232 191 232]
 [107 232 180 246]
 [  1   1   1   1]]
[[ 49 232 191 232]
 [106   0 180 246]
 [  1   1   1   1]]
[[ 50   0 192 233]
 [106   0 180 245]
 [  1   1   1   1]]
[[ 52 232 193 234]
 [104 232 179 244]
 [  1   1   1   1]]
[[ 53   0 194 235]
 [104   0 180 242]
 [  1   1   1   1]]
[[ 59   0 200 

[[220 232 100 216]
 [176 232 177  52]
 [  1   1   1   1]]
[[216 232 101 210]
 [168   0 173  53]
 [  1   1   1   1]]
[[211   0  99 206]
 [168   0 173  56]
 [  1   1   1   1]]
[[208 232  98 203]
 [168   0 173  58]
 [  1   1   1   1]]
[[204   0  96 200]
 [170   0 174  62]
 [  1   1   1   1]]
[[202 232  96 199]
 [172   0 175  66]
 [  1   1   1   1]]
[[199   0  96 197]
 [177 232 178  74]
 [  1   1   1   1]]
[[195   0  95 194]
 [179   0 180  79]
 [  1   1   1   1]]
[[194 232  95 193]
 [179   0 179  80]
 [  1   1   1   1]]
[[195   0  97 194]
 [181   0 180  84]
 [  1   1   1   1]]
[[ 17 232 100  14]
 [163 232 158 247]
 [  1   1   1   1]]
[[ 18 232 101  16]
 [166   0 161 249]
 [  1   1   1   1]]
[[ 21   0 103  17]
 [164   0 160 247]
 [  1   1   1   1]]
[[ 24   0 105  18]
 [164 232 162 247]
 [  1   1   1   1]]
[[ 27   0 107  21]
 [169   0 167 250]
 [  1   1   1   1]]
[[ 25 232 106  21]
 [170   0 166 251]
 [  1   1   1   1]]
[[198 232 105 195]
 [185   0 184  93]
 [  1   1   1   1]]
[[199   0 105 

 [  1   1   1   1]]
[[231 232  83 211]
 [135   0 140 255]
 [  1   1   1   1]]
[[230   0  86 211]
 [128   0 135 253]
 [  1   1   1   1]]
[[226 232  88 209]
 [120 232 134 253]
 [  1   1   1   1]]
[[203 232  88 207]
 [ 98   0 125   2]
 [  1   1   1   1]]
[[231   0  84 213]
 [132   0 138 254]
 [  1   1   1   1]]
[[228 232  89 208]
 [122   0 136 252]
 [  1   1   1   1]]
[[224 232  94 213]
 [107   0 126 249]
 [  1   1   1   1]]
[[224 232  91 202]
 [120   0 142 250]
 [  1   1   1   1]]
[[233 232  87 220]
 [129   0 131 250]
 [  1   1   1   1]]
[[236   0  89 213]
 [133 232 139 250]
 [  1   1   1   1]]
[[236 232  93 216]
 [112   0 126 247]
 [  1   1   1   1]]
[[233 232  90 214]
 [122   0 133 249]
 [  1   1   1   1]]
[[230 232  92 214]
 [118 232 130 250]
 [  1   1   1   1]]
[[233 232  95 210]
 [117 232 134 245]
 [  1   1   1   1]]
[[228 232  92 211]
 [117   0 132 250]
 [  1   1   1   1]]
[[192 232 109 208]
 [ 38   0 100 248]
 [  1   1   1   1]]
[[224 232  93 209]
 [119   0 132 253]
 [  1   1   1 

[[ 36 232 102  22]
 [ 69   0  91 133]
 [  1   1   1   1]]
[[ 35   0 102  23]
 [ 69 232  89 133]
 [  1   1   1   1]]
[[ 35   0 102  23]
 [ 69 232  89 134]
 [  1   1   1   1]]
[[ 35 232 102  23]
 [ 68   0  88 133]
 [  1   1   1   1]]
[[ 36   0 103  24]
 [ 69 232  89 133]
 [  1   1   1   1]]
[[ 37   0 104  26]
 [ 69 232  89 133]
 [  1   1   1   1]]
[[ 37   0 104  26]
 [ 69   0  89 133]
 [  1   1   1   1]]
[[ 36   0 103  26]
 [ 69 232  88 134]
 [  1   1   1   1]]
[[ 35 232 102  25]
 [ 70   0  89 134]
 [  1   1   1   1]]
[[ 33   0 100  22]
 [ 69 232  90 134]
 [  1   1   1   1]]
[[ 33 232 100  20]
 [ 69 232  90 134]
 [  1   1   1   1]]
[[ 32 232  99  20]
 [ 69   0  91 134]
 [  1   1   1   1]]
[[ 31   0  98  17]
 [ 69 232  91 134]
 [  1   1   1   1]]
[[ 30 232  97  15]
 [ 69   0  92 134]
 [  1   1   1   1]]
[[ 29 232  97  14]
 [ 69 232  92 135]
 [  1   1   1   1]]
[[ 28 232  96  13]
 [ 69 232  93 135]
 [  1   1   1   1]]
[[ 27   0  95  12]
 [ 70   0  93 136]
 [  1   1   1   1]]
[[ 27   0  95 

[[223 232 143 217]
 [174   0 174  96]
 [  1   1   1   1]]
[[224   0 144 218]
 [173 232 174  96]
 [  1   1   1   1]]
[[224 232 145 218]
 [173 232 173  96]
 [  1   1   1   1]]
[[225 232 147 219]
 [172 232 173  96]
 [  1   1   1   1]]
[[230   0 152 222]
 [168 232 171  93]
 [  1   1   1   1]]
[[234   0 158 225]
 [165 232 169  89]
 [  1   1   1   1]]
[[243   0 166 230]
 [159   0 167  83]
 [  1   1   1   1]]
[[248 232 172 234]
 [156 232 166  80]
 [  1   1   1   1]]
[[253 232 177 237]
 [153   0 165  77]
 [  1   1   1   1]]
[[253   0 177 237]
 [153   0 164  77]
 [  1   1   1   1]]
[[253   0 177 237]
 [153   0 165  77]
 [  1   1   1   1]]
[[254   0 178 238]
 [152 232 164  76]
 [  1   1   1   1]]
[[255   0 179 239]
 [151   0 164  76]
 [  1   1   1   1]]
[[  0   0 181 239]
 [150 232 164  76]
 [  1   1   1   1]]
[[  1   0 182 239]
 [150 232 164  76]
 [  1   1   1   1]]
[[  0 232 182 239]
 [151 232 165  78]
 [  1   1   1   1]]
[[  0 232 182 239]
 [150 232 164  76]
 [  1   1   1   1]]
[[  0   0 182 

In [6]:
cap.release()
cv2.destroyAllWindows()