In [1]:
import numpy as np
from matplotlib import pyplot as plt
import cv2
import glob

import math
from scipy import linalg
from numpy.linalg import inv
from numpy import linalg as LA
from sklearn import linear_model, datasets
from function import *

In [19]:
# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
objp = np.zeros((21*15,3), np.float32)
objp[:,:2] = np.mgrid[0:21,0:15].T.reshape(-1,2)

In [20]:
# Arrays to store object points and image points from all the images.
objpoints = [] # 3d point in real world space
imgpoints = [] # 2d points in image plane.

images = glob.glob('a.png')

for fname in images:
    img = cv2.imread(fname)
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    
    # Find the chess board corners
    ret, corners = cv2.findChessboardCorners(gray, (21,15),None)

    # If found, add object points, image points (after refining them)
    if ret == True:
        
        # termination criteria
        criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)
        
        objpoints.append(objp)
        cv2.cornerSubPix(gray,corners,(11,11),(-1,-1),criteria)
        imgpoints.append(corners)

        # Draw and display the corners
        cv2.drawChessboardCorners(img, (21,15), corners,ret)
        cv2.imshow('img',img)
        cv2.waitKey(5000000)
    
cv2.destroyAllWindows()

In [6]:
img_p = return_imagepoints()
obj_p = return_objpoints()

obj_p4 = homo_obj4(obj_p)
obj_p3 = homo_obj3(obj_p)
img_p = homo_img(img_p)

print("obj_p3.shape", obj_p3.shape)
print("obj_p4.shape", obj_p4.shape)
print("img_p.shape", img_p.shape)

obj_p3.shape (3, 315)
obj_p4.shape (4, 315)
img_p.shape (3, 315)


In [15]:
# img_p[:2,:].T.shape
# obj_p[:2,:].T.shape
obj_p.shape

(315, 3)

In [3]:
obj_pt3 = obj_p3.T
obj_pt4 = obj_p4.T
img_pt = img_p.T
print("obj_pt.shape", obj_pt3.shape)
print("obj_pt.shape", obj_pt4.shape)
print("img_pt.shape", img_pt.shape)

obj_pt.shape (315, 3)
obj_pt.shape (315, 4)
img_pt.shape (315, 3)


In [4]:
p = projection_matrix_direct(img_pt,obj_pt3)
print(p,"\n")

p_ = projection_matrix3(img_pt,obj_pt3)
print(p_,"\n")

_p = projection_matrix4(img_pt,obj_pt4)
print(_p)

[[ 2.35641141e+01 -1.13180327e-01  1.07795469e+02]
 [ 1.24120961e-01  2.34434472e+01  8.29785775e+01]
 [ 2.21177243e-17 -6.93889390e-17  1.00000000e+00]] 

[[ 2.32708135e+01 -6.48353739e-02  1.08385471e+02]
 [-1.23646156e-02  2.33727681e+01  8.37870163e+01]
 [-5.46339618e-04  1.40990039e-04  1.00000000e+00]] 

[[ 1.36930779e+02 -3.50209450e-01  5.00613492e-02  1.08329258e+02]
 [-5.06145912e-02  1.36930340e+02 -1.36930779e+02  8.37485083e+01]
 [-3.13732526e-03  8.94422047e-04  0.00000000e+00  1.00000000e+00]]


In [5]:
a,b,c = RQ_decomposition(_p)
print("camera_calibration_matrix",a)
print("rotation_matrix",b)
print("translation_matrix",c)

camera_calibration_matrix [[-8.23117244e+03  7.89362395e+03 -4.03944076e+04]
 [-0.00000000e+00  5.82300214e+04  1.15225601e+04]
 [-0.00000000e+00 -0.00000000e+00  1.00000000e+00]]
rotation_matrix [[ 0.19762446  0.69319872  0.69312345]
 [-0.19003129 -0.66656449  0.7208189 ]
 [ 0.96168221 -0.27416659  0.        ]]
translation_matrix [-5.10903824 -0.19644182  1.        ]


In [22]:
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(obj_p, img_p[:2,:], gray.shape[::-1],None,None)

TypeError: objectPoints is not a numpy array, neither a scalar

In [11]:
# test = np.matmul(_p,obj_p4)
# test[:,:5]
# img_p[:,:5]
# ptp = np.matmul(_p.T,_p)
# ptpinv = inv(ptp)
# pinv = np.matmul(ptpinv,_p.T)
# test4 = np.matmul(pinv, img_p)
# test4[:,:5]
# obj_p4[:,:5]

--------------------------------------

---------------------------------------